Update snyk-security-Jenkinsfile.yml

diff --git a/.github/workflows/snyk-security-Jenkinsfile.yml b/.github/workflows/snyk-security-Jenkinsfile.yml
--- a/.github/workflows/snyk-security-Jenkinsfile.yml
+++ b/.github/workflows/snyk-security-Jenkinsfile.yml
@@ -1,12 +1,45 @@
-name: Snyk Security Scan
-
-on: [push]
-
+name: SonarQube Analysis and Snyk Scan
+on:
+  push:
+    branches:
+      - main
 jobs:
-  snyk_scan:
+  sonarqube_analysis:
     runs-on: ubuntu-latest
-    
     steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+      - name: Set up Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: '20'
+      - name: Install dependencies
+        run: cd WWA-backend-master && npm install
+      - name: Run Jest tests with coverage
+        run: cd WWA-backend-master && npm test -- --coverage || true
+        # Run tests with coverage, ignoring failures with '|| true'
+      - name: Set up JDK 17
+        uses: actions/setup-java@v2
+        with:
+          java-version: '17'
+          distribution: 'adopt'
+#########################################
+      - name: SonarQube Scan
+        uses: SonarSource/sonarqube-scan-action@7295e71c9583053f5bf40e9d4068a0c974603ec8
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
+        with:
+          args:
+            -Dsonar.projectKey=group2
+            -Dsonar.sources=.
+            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
+            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
+            -Dsonar.javascript.lcov.reportPaths=WWA-backend-master/coverage/lcov.info
+            
+      # Snyk security scan step for web
+
       - name: Checkout repository
         uses: actions/checkout@v2
 
@@ -23,10 +56,35 @@ jobs:
         continue-on-error: true
         env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
-        working-directory: WWA-backend-master
+        working-directory: 
+                WWA-backend-master
+                WWA-frontend-master
+
 
       - name: Snyk Monitor
         run: snyk monitor --org=shreyashettys202 --project-name='Project-Group3'
         env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
-        working-directory: WWA-backend-master
+        working-directory: 
+                WWA-backend-master
+                WWA-frontend-master
+
+
+  # Snyk security scan step for Code Scanning
+
+      - name: Set up Node.js
+        uses: actions/setup-node@v2
+        with:
+          node-version: '20' # Adjust the version as needed
+      - name: Run Snyk to check for vulnerabilities
+        uses: snyk/actions/node@master
+        continue-on-error: true
+        with:
+          args: ./WWA-backend-master --sarif-file-output=snyk.sarif
+        env:
+          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+      - name: Upload SARIF to GitHub Security Center
+        uses: github/codeql-action/upload-sarif@v3
+        with:
+          sarif_file: snyk.sarif
+          category: 'Snyk Open Source Unique Category'
