Update sonar-snyk.yml

diff --git a/.github/workflows/sonar-snyk.yml b/.github/workflows/sonar-snyk.yml
--- a/.github/workflows/sonar-snyk.yml
+++ b/.github/workflows/sonar-snyk.yml
@@ -1,30 +1,33 @@
 name: JSDoc
+
 on:
   push:
     branches:
       - main
+
 jobs:
   JSDoc_doc:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
+      
       - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
           node-version: '20'
-      - name: Install dependencies
-        run: cd WWA-backend-master && npm install
-      - name: Run Jest tests with coverage
-        run: cd WWA-backend-master && npm test -- --coverage || true
-        # Run tests with coverage, ignoring failures with '|| true'
-      - name: Set up JDK 17
-        uses: actions/setup-java@v2
-        with:
-          java-version: '17'
-          distribution: 'adopt'
- ########################################JSDoc
-      - name: Build
+      
+      # Assuming your frontend might also need dependency installation.
+      - name: Install frontend dependencies
+        run: npm install
+        working-directory: WWA-frontend-master
+      
+      # If your frontend also has tests you wish to run.
+      - name: Run frontend Jest tests with coverage
+        run: npm test -- --coverage || true # Ignore test failures
+        working-directory: WWA-frontend-master
+      
+      - name: Generate JSDoc documentation
         uses: andstor/jsdoc-action@v1
         with:
           source_dir: ./WWA-frontend-master/src
@@ -32,9 +35,9 @@ jobs:
           config_file: conf.json
           template: minami
           front_page: README.md
-
-      - name: Deploy
+      
+      - name: Deploy to GitHub Pages
         uses: peaceiris/actions-gh-pages@v3
         with:
           deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
-          publish_dir: ./out
+          publish_dir: ./WWA-frontend-master/out
